const options = [
  { id: 1, name: "세탁기", category: "가전제품" },
  { id: 2, name: "에어컨", category: "가전제품" },
  { id: 3, name: "냉장고", category: "가전제품" },
  { id: 4, name: "전자레인지", category: "가전제품" },
  { id: 5, name: "TV", category: "가전제품" },
  { id: 6, name: "가스레인지", category: "가전제품" },
  { id: 7, name: "책장", category: "가구" },
  { id: 8, name: "옷장", category: "가구" },
  { id: 9, name: "신발장", category: "가구" },
  { id: 10, name: "책상/의자", category: "가구" },
  { id: 11, name: "침대", category: "가구" },
  { id: 12, name: "CCTV", category: "기타" },
  { id: 13, name: "도어락", category: "기타" },
  { id: 14, name: "열쇠", category: "기타" },
  { id: 15, name: "주차장", category: "기타" },
  { id: 16, name: "반려동물", category: "기타" },
  { id: 17, name: "베란다", category: "기타" },
  { id: 18, name: "방충망", category: "기타" },
  { id: 19, name: "방범창", category: "기타" },
  { id: 20, name: "블라인드/커튼", category: "기타" },
];
